apiVersion: v1
kind: Service
metadata:
  name: wiremockdemo
spec:
  ports:
    - name: http
      port: 9200
      protocol: TCP
      targetPort: 8080
  selector:
    app: wiremockdemo
  type: LoadBalancer
